package com.example.squadapp

import Game
import GameAdapter
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.provider.MediaStore
import android.util.Log
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.fragment.app.Fragment
import com.example.squadapp.entities.Post
import com.google.android.material.button.MaterialButton
import com.google.android.material.textfield.MaterialAutoCompleteTextView
import com.google.android.material.textfield.TextInputEditText
import android.widget.ImageView
import com.example.squadapp.models.Model
import java.util.Date

class PostFragment : Fragment(R.layout.fragment_post) {

    private lateinit var imagePreview: ImageView
    private lateinit var imagePlaceholder: android.widget.LinearLayout
    private lateinit var imageBoxContainer: android.widget.FrameLayout
    private lateinit var gamesDropdown: MaterialAutoCompleteTextView
    private lateinit var descriptionText: TextInputEditText
    private lateinit var publishBtn: MaterialButton

    private var selectedImageUri: Uri? = null
    private var isPublishing = false

    private lateinit var gameAdapter: GameAdapter
    private val gameList = mutableListOf<Game>()

    private val pickImageLauncher = registerForActivityResult(
        ActivityResultContracts.StartActivityForResult()
    ) { result ->
        if (result.resultCode == android.app.Activity.RESULT_OK) {
            val data = result.data
            selectedImageUri = data?.data
            if (selectedImageUri != null) {
                imagePreview.setImageURI(selectedImageUri)
                imagePreview.visibility = View.VISIBLE
                imagePlaceholder.visibility = View.GONE
            }
        }
    }

    override fun onCreateView(
        inflater: android.view.LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_post, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        // Initialize views
        imagePreview = view.findViewById(R.id.post_image_preview)
        imagePlaceholder = view.findViewById(R.id.image_placeholder)
        imageBoxContainer = view.findViewById(R.id.image_box_container)
        gamesDropdown = view.findViewById(R.id.games_dropdown)
        descriptionText = view.findViewById(R.id.description_text)
        publishBtn = view.findViewById(R.id.publish_btn)

        // Set up game dropdown with filtering
        setupGameDropdown()

        // Set up image box to open gallery directly on click
        imageBoxContainer.setOnClickListener {
            val galleryIntent = Intent(Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI)
            pickImageLauncher.launch(galleryIntent)
        }

        // Set up publish button
        publishBtn.setOnClickListener {
            if (!isPublishing) {
                publishPost()
            }
        }
    }

    private fun setupGameDropdown() {
        gameAdapter = GameAdapter(requireContext(), gameList)
        gamesDropdown.setAdapter(gameAdapter)
        gamesDropdown.dropDownHeight = 850

        gamesDropdown.setOnItemClickListener { _, _, position, _ ->
            gamesDropdown.setText(gameList[position].name, false)
        }
    }

    private fun publishPost() {
        val game = gamesDropdown.text.toString()
        val description = descriptionText.text.toString()

        if (game.isEmpty()) {
            Toast.makeText(context, "Please select a game", Toast.LENGTH_SHORT).show()
            return
        }

        if (description.isEmpty()) {
            Toast.makeText(context, "Please add a description", Toast.LENGTH_SHORT).show()
            return
        }

        // Get current user from MainActivity
        val mainActivity = activity as? MainActivity
        if (mainActivity == null) {
            Toast.makeText(context, "Error: Could not get user information", Toast.LENGTH_SHORT).show()
            return
        }

        val currentUser = mainActivity.currentUser

        // Create post object
        val post = Post(
            id = "", // Will be generated by Firestore
            image = 0, // No local image resource ID when fetching from gallery
            user = currentUser,
            description = description,
            creationTime = Date(System.currentTimeMillis())
        )

        // Disable publish button and show loading state
        isPublishing = true
        publishBtn.isEnabled = false
        publishBtn.text = "Publishing..."

        // Publish post to server
        Model.shared.addPost(post) { success, message ->
            isPublishing = false
            publishBtn.isEnabled = true
            publishBtn.text = "Publish Post"

            if (success) {
                Log.d("PostFragment", "Post published successfully")
                Toast.makeText(context, message, Toast.LENGTH_SHORT).show()

                // Reset form and navigate back to home
                resetForm()
                navigateToHome()
            } else {
                Log.e("PostFragment", "Failed to publish post: $message")
                Toast.makeText(context, message, Toast.LENGTH_LONG).show()
                // Form is NOT reset, user can try again
            }
        }
    }

    private fun navigateToHome() {
        // Navigate back to HomeFragment
        parentFragmentManager.beginTransaction().apply {
            replace(R.id.fragment_container, HomeFragment())
            commit()
        }
    }

    private fun resetForm() {
        selectedImageUri = null
        imagePreview.setImageBitmap(null)
        imagePreview.visibility = View.GONE
        imagePlaceholder.visibility = View.VISIBLE
        gamesDropdown.text.clear()
        descriptionText.text?.clear()
    }
}


