package com.example.squadapp.entities

import java.util.Date

/**
 * NewPost - Entity for creating new posts WITHOUT an ID
 * Used for inserting new posts into the database (ID will be generated by Firestore)
 */
data class NewPost(
    val image: Int,  // drawable resource ID
    val userId: String,  // Reference to user ID
    val description: String,
    val creationTime: Date,
    val gameId: Int
) {
    companion object {
        /**
         * Serializes NewPost to Map for database insertion (without ID)
         * Firestore will auto-generate the ID
         */
        fun serialize(newPost: NewPost): Map<String, Any?> {
            return hashMapOf(
                Post.POST_IMAGE to newPost.image,
                Post.POST_USER to newPost.userId, // Store user ID as foreign key reference
                Post.POST_DESCRIPTION to newPost.description,
                Post.POST_CREATION_TIME to newPost.creationTime,
                Post.POST_GAME_ID to newPost.gameId
            )
        }
    }
}

