package com.example.squadapp.entities

import com.example.squadapp.utils.PasswordHasher

/**
 * NewUser - Entity for creating new users WITHOUT an ID
 * Used for inserting new users into the database (ID will be generated by Firestore)
 * Contains password field for authentication and database storage
 */
data class NewUser(
    val profileImage: Int,  // drawable resource ID
    val username: String,
    val password: String,
    val discordTag: String
) {
    companion object {
        /**
         * Serializes NewUser to Map for database insertion (without ID)
         * Firestore will auto-generate the ID
         */
        fun serialize(newUser: NewUser): Map<String, Any?> {
            return hashMapOf(
                UserDTO.USER_PROFILE_IMAGE to newUser.profileImage,
                UserDTO.USER_USERNAME to newUser.username,
                UserDTO.USER_PASSWORD to newUser.password,
                UserDTO.USER_DISCORD_TAG to newUser.discordTag
            )
        }

        /**
         * Creates a new NewUser with hashed password
         * Takes a NewUser with plain password and returns a NewUser with hashed password
         * @param newUser NewUser with plain password
         * @return NewUser with hashed password
         */
        fun withHashedPassword(newUser: NewUser): NewUser {
            val hashedPassword = PasswordHasher.hashPassword(newUser.password)
            return NewUser(
                profileImage = newUser.profileImage,
                username = newUser.username,
                password = hashedPassword,
                discordTag = newUser.discordTag
            )
        }
    }
}

